### PR TITLE
Improvements v2

### PR DESCRIPTION
**Pull request by BryceBarbara**
## Changes

* Did quite a bit of refactoring to make the source code easier to extend in the future
* Improved the typing situation across the codebase
* Added types for the **kaitai-struct** packages since they didn't have any 🤷‍♂️
* Removed the local copies of **kaitai-struct-compiler** and switched to using the npm packages
* Added icons to some commands so they can be used in toolbars
* Added a command that lets you pick files from you workspace and then immediately analyze it
* Added use of the `package.nls.json` stuff with the goal of eventually supporting translations

Oh and this addresses:
* #13 
* #12

### CODE REVIEW

**Comment by BryceBarbara** [comment]
Wow, that's the best add/removed lines ratio for a PR I've ever achieved!

**Comment by BryceBarbara** [comment]
@fudgepop01 Tagging you again cause it worked last time 🤞

**Comment by fudgepop01** [comment]
Looks great! I'll merge it right away 👍

**Comment by fudgepop01** [comment]
Hello! Real quick I wanted to apologize for merging and implementing this incorrectly for so long. I only recently caught my mistakes now and will be updating the extension with your changes **properly** now at last. Once again, thank you very much for your contribution and refactoring! The work you put in is fantastic👍

**Pull request merged**
