### PR TITLE
Improvements v1

### PR DESCRIPTION
**Pull request by BryceBarbara**
I'm planning on using this in some personal projects but need to improve it a bit before it can be effectively used. This PR contains a collection of initial improvements I made to the project.

* Switched to using [esbuild](https://esbuild.github.io/) instead of webpack. The results are very similar, but esbuild takes less than 1 second when webpack takes over 5.
* Added `contributes.languages` section in `package.json` so users no longer need to manually set `files.associations` . The pro-tip from the readme can be removed once we verify it works for other users too.
* Setup `contributes.yamlValidation` so users no longer have to set `yaml.schemas`.
* Fixed the letter casing used in the VSCode commands
* Changed the cursor for the "Settings" handle of the hex editor so its easier to recognize as a clickable thing

### CODE REVIEW

**Comment by BryceBarbara** [comment]
@fudgepop01 Are you still maintaining this repo? If not, I'd be happy to take over/fork this and continue where you left off.

**Comment by fudgepop01** [comment]
Oh wow! I'm terribly sorry - I didn't realize others were still using this (I thought it had been replaced by the python based visualizer and such). Thank you so much for the contributions! I'll quickly test and merge this right away

edit: I'll also update and fix the importing of some of the javascript that I was apparently working on in the past ahahah

**Comment by BryceBarbara** [comment]
@fudgepop01 Although the python one has more features, it's far easier to recommend a VS Code extension to developers working on a reverse engineering project. It also prevents us from having python as a developer dependency.

Just wanted to share my reasoning for use this to shed some light on the situation :)

**Comment by fudgepop01** [comment]
I see! That makes sense. I just managed to quickly track down and fix a bug related to where the regions were rendered in the hex editor, as well as where the listed KS Explorer nodes would take you when clicked. Now that that's done (and pushed at last after I remembered how to properly merge a branch), it should be much easier to recommend :D 

Thanks again for your contributions!

**Pull request merged**
